apiVersion: batch/v1
kind: Job
metadata:
  name: myjob
spec:
  activeDeadlineSeconds: 10
  # backoffLimit: 3 
  # completions: 5
  # parallelism: 2
  template:
    metadata:
      name: job-pod
      labels:
        app: myapp
    spec:
      containers:
      - name: myjob-container
        image: busybox
        command: ["sleep","60"]
      restartPolicy: Never