apiVersion: v1
kind: Pod
metadata:
  name: msql
spec:
    containers:
    - name: sql-container
      image: mysql
      envFrom:
      - configMapRef:
          name: cm1
      # env:
      # - name: MYSQL_ROOT_PASSWORD
      #   valueFrom:
      #     configMapKeyRef:
      #       key: MYSQL_ROOT_PASSWORD
      #       name: cm1
      # - name: MYSQL_PASSWORD
      #   valueFrom:
      #     configMapKeyRef:
      #       key: MYSQL_PASSWORD
      #       name: cm1

      # - name: MYSQL_USER
      #   valueFrom:
      #     configMapKeyRef:
      #       key: MYSQL_USER
      #       name: cm1

      