apiVersion: v1
kind: Pod
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Pod","metadata":{"annotations":{},"labels":{"app":"myapp"},"name":"new-pod","namespace":"default"},"spec":{"containers":[{"image":"nginx","name":"nginx-container"},{"command":["sleep","1000"],"image":"busybox","name":"busybox-container"}]}}
  labels:
    app: myapp
  name: new-pod
  namespace: default
spec:
  containers:
  - image: nginx
    name: nginx-container
  - command:
    - sleep
    - "1000"
    image: busybox
    name: busybox-container