apiVersion: v1
kind: Pod
metadata:
  name: myapp
  labels:
    app: myapp
spec:
  initContainers:
  - name: init-container1
    image: alpine
    command: ["sleep","5"]
  
  - name: init-container2
    image: busybox
    command: ["sleep","5"]


  containers:
  - name: nginx-container
    image: nginx
  